# Generated by Django 3.1.1 on 2020-09-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('topic1', models.CharField(max_length=100)),
                ('topic2', models.CharField(max_length=100)),
                ('topic3', models.CharField(max_length=100)),
                ('topic4', models.CharField(max_length=100)),
                ('topic5', models.CharField(max_length=100)),
            ],
        ),
    ]
