# Generated by Django 3.1.1 on 2020-09-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0005_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='month',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='topic',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
