# Generated by Django 3.1.1 on 2020-09-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0006_auto_20200923_1933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
