# Generated by Django 3.1.1 on 2020-09-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NewsApp', '0009_delete_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic1', models.TextField(null=True)),
                ('topic2', models.TextField(null=True)),
                ('topic3', models.TextField(null=True)),
                ('topic4', models.TextField(null=True)),
                ('topic5', models.TextField(null=True)),
                ('topic6', models.TextField(null=True)),
                ('topic7', models.TextField(null=True)),
                ('topic8', models.TextField(null=True)),
                ('topic9', models.TextField(null=True)),
                ('topic10', models.TextField(null=True)),
                ('topic11', models.TextField(null=True)),
                ('topic12', models.TextField(null=True)),
                ('topic13', models.TextField(null=True)),
                ('topic14', models.TextField(null=True)),
                ('topic15', models.TextField(null=True)),
                ('topic16', models.TextField(null=True)),
                ('topic17', models.TextField(null=True)),
                ('topic18', models.TextField(null=True)),
                ('topic19', models.TextField(null=True)),
                ('topic20', models.TextField(null=True)),
            ],
        ),
    ]
