# Generated by Django 3.1.1 on 2020-09-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0010_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
